[project]
name = "assignment1"
version = "0.1.0"
description = "CSDS 413 Assignment 1"
authors = [
    {name = "Jacob Anderson", email = "jma195@case.edu"},
    {name = "Wiam Skakri", email = "wxs428@case.edu"}
]

[tool.poetry.dependencies]
python = "^3.12"
pandas = "^2.3.2"
seaborn = "^0.13.2"
matplotlib = "^3.10.6"
scipy = "^1.16.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
